name: Generate Pi-hole Blocklist

on:
  schedule:
    - cron: '0 0 * * *'  # 每天一次执行
  workflow_dispatch:

jobs:
  generate-blocklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Sing-box
      run: |
        curl -fsSL https://sing-box.app/install.sh | sh

    - name: Create rule-set directory
      run: |
        mkdir -p rule-set

    - name: Generate geosite-torrent-websites.json
      run: |
        jq -n --argjson domains "$(
          curl -fsSL https://raw.githubusercontent.com/sakib-m/Pi-hole-Torrent-Blocklist/main/all-torrent-websites.txt |
          grep -v '^#' |
          grep -v '^$' |
          jq -R . |
          jq -s .
        )" '{"version": 3,"rules": [{"domain": $domains}]}' > rule-set/geosite-torrent-websites.json

    - name: Generate geosite-torrent-trackers.json
      run: |
        jq -n --argjson domains "$(
          curl -fsSL https://raw.githubusercontent.com/sakib-m/Pi-hole-Torrent-Blocklist/main/all-torrent-trackers.txt |
          grep -v '^#' |
          grep -v '^$' |
          jq -R . |
          jq -s .
        )" '{"version": 3,"rules": [{"domain": $domains}]}' > rule-set/geosite-torrent-trackers.json

    - name: Compile geosite-torrent-websites.json to geosite-torrent-websites.srs
      run: |
        sing-box rule-set compile --output rule-set/geosite-torrent-websites.srs rule-set/geosite-torrent-websites.json

    - name: Compile geosite-torrent-trackers.json to geosite-torrent-trackers.srs
      run: |
        sing-box rule-set compile --output rule-set/geosite-torrent-trackers.srs rule-set/geosite-torrent-trackers.json

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # 检查是否有文件变动
        git status
        
        # 如果有变动，执行 git add 和提交操作
        git add rule-set/*
        git diff --cached --quiet || git commit -m "Update Pi-hole blocklist and binary rules"
        
        # 如果有提交则推送
        git push
